baseUrl: "http://www.fangdi.com.cn/complexpro.asp?districtID=11&Region_ID=&projectAdr=&projectName=&startCod=&buildingType=0&houseArea=0&averagePrice=0&selState=&selCircle=0"
httpConnectTimeout: 100000
httpReadTimeout:  100000
httpWriteTimeout:  100000
httpMethod:  POST
#httpHeader:
postFormData: 
  - districtID
  - "11"
  - Region_ID
  - ""
  - projectAdr
  - ""
  - projectName
  - ""
  - startCod
  - ""
  - buildingType
  - "0"
  - houseArea
  - "0"
  - averagePrice
  - "0"
  - selState
  - ""
  - selCircle
  - "0"
  - page
  - "1"
#httpBody: "<PDoc Tag='GetYSPrjInfo' />"
basePagingTaskNum: 1
basePageStart: 1
basePageEnd: -1 #less than 0 means end is tatal pages
basePageUrl: "http://www.fangdi.com.cn/complexpro.asp?districtID=11&Region_ID=&projectAdr=&projectName=&startCod=&buildingType=0&houseArea=0&averagePrice=0&selState=&selCircle=0&page=[PAGENO]"
basePageInfoType: HTML_ELE_EXTRAT
basePageInfoPatternStr: (\\d+)页
basePageInfoSelector: "#AspNetPager1 > table > tbody > tr > td:nth-child(1)"